#!/bin/bash
set -eu
[[ $(whoami) = "root" ]] || { echo "You must be root to run this script."; exit 1; }

use_realfs=false
changes_size=$(du -s /run/initramfs/memory/data/slax/changes/ | awk '{print $1}')
usable_mem=$(grep MemFree /proc/meminfo | awk '{print $2}')

echo "Size of changes: $changes_size kB, Usable memory: $usable_mem kB"
if [[ $changes_size -gt $usable_mem ]]; then
    echo "INFO: Insufficient RAM, using real file system for \$TMP folder."
    use_realfs=true
fi

if [[ "$use_realfs" = true ]]; then
    TMP=/run/initramfs/memory/data/savechanges-tmp.$$
else
    TMP=/tmp/changes.$$
fi
EXCLUDE="^\$|/\$|[.]wh[.][.]wh[.]orph/|^[.]wh[.][.]wh[.]plnk/|^[.]wh[.][.]wh[.]aufs|^var/cache/|^var/backups/|^var/tmp/|^var/log/|^var/lib/apt/|^var/lib/dhcp/|^var/lib/systemd/|^sbin/fsck[.]aufs|^etc/resolv[.]conf|^root/[.]Xauthority|^root/[.]xsession-errors|^root/[.]fehbg|^root/[.]fluxbox/lastwallpaper|^root/[.]fluxbox/menu_resolution|^etc/mtab|^etc/fstab|^boot/|^dev/|^mnt/|^proc/|^run/|^sys/|^tmp/"
CHANGES=/run/initramfs/memory/changes

if [ "${1:-}" = "" ]; then
   echo ""
   echo "savechanges - save all changed files in a compressed filesystem bundle"
   echo "            - excluding some predefined files such as /etc/mtab,"
   echo "              temp & log files, empty directories, apt cache, and such"
   echo ""
   echo "Usage:"
   echo "        $0 [ target_file.sb ] [ changes_directory ]"
   echo ""
   echo "If changes_directory is not specified, /run/initramfs/memory/changes is used."
   echo ""
   exit 1
fi

if [ ! "${2:-}" = "" ]; then
   CHANGES="$2"
fi

# exclude the save_file itself of course
EXCLUDE="$EXCLUDE|^""$(readlink -f "$1" | cut -b 2- | sed -r "s/[.]/[.]/")""\$"

CWD=$(pwd)

cd $CHANGES || exit

mkdir -p $TMP
[[ "$use_realfs" = false ]] && mount -t tmpfs tmpfs $TMP

cleanup(){
    echo "Cleaning up $TMP"
    if [[ "$use_realfs" == false ]]; then
        umount $TMP
        rmdir $TMP
    else
        [[ -d $TMP ]] && rm -r $TMP
    fi
}

trap cleanup SIGINT EXIT

find \( -type d -printf "%p/\n" , -not -type d -print \) \
  | sed -r "s/^[.]\\///" | egrep -v "$EXCLUDE" \
  | while read FILE; do
    cp --parents -afr "$FILE" "$TMP"
done

cd $CWD

mksquashfs $TMP "$1" -comp xz -b 1024K -always-use-fragments -noappend
